name: Integration Tests

on: [push, pull_request]

env:
  TEST_BROWSER_HEADLESS: 1
  CI: 1
  OPENSEARCH_VERSION: 3.0.0
  PLUGIN_NAME: opensearch-security
  PLUGIN_VERSION: 3.0.0.0

jobs:
  tests:
    name: Run integration tests
    strategy:
      fail-fast: false
      matrix:
        #os: [ ubuntu-latest , windows-latest ]
        os: [ windows-latest ]
        #os: [ ubuntu-latest ]
        jdk: [11]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - uses: browser-actions/setup-geckodriver@latest
      - run: geckodriver --version

      # Browser-action version does not work on Windows
      - name: Set up Firefox browser
        uses: abhi1693/setup-browser@main
        with:
          browser: firefox
          version: latest

      # Must be set for Windows to process
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      # Download OpenSearch Security
      - name: Download OpenSearch Security for Windows
        uses: peternied/download-file@v2
        if: ${{ runner.os == 'Windows' }}
        with:
          url: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/${{ env.OPENSEARCH_VERSION }}/latest/windows/x64/zip/builds/opensearch/plugins/${{ env.PLUGIN_NAME }}-${{ env.PLUGIN_VERSION }}.zip

      - name: Download OpenSearch Security for Linux
        uses: peternied/download-file@v2
        if: ${{ runner.os == 'Linux' }}
        with:
          url: https://ci.opensearch.org/ci/dbc/distribution-build-opensearch/${{ env.OPENSEARCH_VERSION }}/latest/linux/x64/tar/builds/opensearch/plugins/${{ env.PLUGIN_NAME }}-${{ env.PLUGIN_VERSION }}.zip

      - name: Rename Plugin File
        run: mv ${{ env.PLUGIN_NAME }}-${{ env.PLUGIN_VERSION }}.zip ${{ env.PLUGIN_NAME }}.zip

      - name: Create Setup Script for Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          cat > setup.sh <<'EOF'
          chmod +x  ./opensearch-${{ env.OPENSEARCH_VERSION }}-SNAPSHOT/plugins/${{ env.PLUGIN_NAME }}/tools/install_demo_configuration.sh 
          /bin/bash -c "./opensearch-${{ env.OPENSEARCH_VERSION }}-SNAPSHOT/plugins/${{ env.PLUGIN_NAME }}/tools/install_demo_configuration.sh -y"
          EOF

      - name: Create Setup Script for Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          New-Item .\setup.bat -type file
          Set-Content .\setup.bat -Value "powershell.exe .\opensearch-${{ env.OPENSEARCH_VERSION }}-SNAPSHOT\plugins\${{ env.PLUGIN_NAME }}\tools\install_demo_configuration.bat -y"
          Get-Content .\setup.bat

      - name: Run Opensearch with A Single Plugin
        uses: scrawfor99/security/.github/actions/start-opensearch-with-one-plugin@modify-for-dash-config
        with:
          opensearch-version: ${{ env.OPENSEARCH_VERSION }}
          plugin-name: ${{ env.PLUGIN_NAME }}
          setup-script-name: setup

      - id: install-dashboards
        uses: ./.github/actions/install-dashboards
        with:
          plugin_name: security-dashboards-plugin

      - name: Start Dashboards in background on Linux
        if: ${{ runner.os == 'Linux' }}
        run: node scripts/build_opensearch_dashboards_platform_plugins.js
        working-directory: ${{ steps.install-dashboards.outputs.dashboards-directory }}

      - name: Run integration tests on Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          echo "Check if OpenSearch is running on Linux"
          curl -XGET https://localhost:9200 -u 'admin:admin' -k
          yarn test:jest_server --coverage
        working-directory: ${{ steps.install-dashboards.outputs.plugin-directory }}

      - name: Run integration tests on Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          echo "Check if OpenSerch is running on Windows"
          curl -XGET https://localhost:9200 -u 'admin:admin' -k
          yarn test:jest_server --coverage
        working-directory: ${{ steps.install-dashboards.outputs.plugin-directory }}